version: '3.1'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_DATABASE: laravel_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
